### ISSUE TITLE
Use Paper/Taco as Base Project

### ISSUE THREAD

**Issue by Proximyst** [Proximyst/Proj.-Spigot-Vult#11]
Paper already brings many improvements to spigot (api and implementations).
I think it would be better to base of of that so we don't need to backport paper changes. 

Taco requested by @electronicboy
Paper requested by @MiniDigger

**Comment by electronicboy** [comment]
I'm saying use paper, TacoSpigot just has all of the tooling that you need that you can literally just rip out of their project.
