### ISSUE TITLE
Entity Unload Event 

### ISSUE THREAD

**Issue by Proximyst** [Proximyst/Proj.-Spigot-Vult#4]
Text: An unload event for every entity when the world/chunk is unloaded, or the entity itself.
Very useful for storing references to entities instead of weak references.

@ysl3000 : 
```java
public enum EntityUnloadCause{
CHUNK_UNLOAD,CUSTOM,OTHER_ENTITY;
}
```

O_E = player, primed_tnt,...

**Comment by ysl3000** [comment]
Paper or Taco has this event, I think.

**Comment by Proximyst** [comment]
Done. No EntityUnloadCause way to wayyy too many calls of unload.
Maybe when the project grows.
